export const ADD_ALERT = 'ADD_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const FETCH_PROGRAMS = 'FETCH_PROGRAMS';
export const FETCHED_PROGRAMS = 'FETCHED_PROGRAMS';
export const RUN_PROGRAM = 'RUN_PROGRAM';