export const ADD_ALERT = 'ADD_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REQUEST_PROGRAMS = 'REQUEST_PROGRAMS';
export const RECEIVE_PROGRAMS = 'RECEIVE_PROGRAMS';
export const RECEIVE_PROGRAM = 'RECEIVE_PROGRAM';
export const RUN_PROGRAM = 'RUN_PROGRAM';
