export const ADD_ALERT = 'ADD_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REQUEST_PROGRAMS = 'REQUEST_PROGRAMS';
export const RECEIVE_PROGRAMS = 'RECEIVE_PROGRAMS';
export const RUN_PROGRAM = 'RUN_PROGRAM';
export const UPDATE_PROGRAM = 'UPDATE_PROGRAM';

export const REQUEST_SECTIONS = 'REQUEST_SECTIONS';
export const RECEIVE_SECTIONS = 'RECEIVE_SECTIONS';
export const RUN_SECTION = 'RUN_SECTION';
export const TOGGLE_SECTION = 'TOGGLE_SECTION';
